package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.shxt.szqz.database.*;
import com.shxt.szqz.beans.*;

public final class album3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=gbk");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'album3.jsp' starting page</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />\r\n");
      out.write("<title>无标题文档</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".te { border:1px solid #3399ff; height:20px;right 3px no-repeat;}\r\n");
      out.write(".area \r\n");
      out.write("{ border:1px solid #3399ff; overflow:auto; background:#fff url(pictures/sygb.jpg) right bottom no-repeat;color:black;font-size:12px}\r\n");
      out.write(".se\r\n");
      out.write("{\r\n");
      out.write("height: 20px;\r\n");
      out.write("color:#000000\r\n");
      out.write("line-height: 100%;\r\n");
      out.write("border:1px solid #3399ff;\r\n");
      out.write("}\r\n");
      out.write("  a { text-decoration: none}\r\n");
      out.write("a:hover { text-decoration:underline;color:#666666}\r\n");
      out.write("  .STYLE1 {\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-family: \"幼圆\";\r\n");
      out.write("}\r\n");
      out.write(".ch{border:none;background:url(pictures/photo3fb.jpg);  left top no-repeat;width:48px; height:21px; }\r\n");
      out.write("  a { text-decoration: none}\r\n");
      out.write("a:hover { text-decoration:underline;color:#666666}\r\n");
      out.write("  .STYLE1 {\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-family: \"幼圆\";\r\n");
      out.write("}\r\n");
      out.write(".ch{border:none;background:url(pictures/photo3fb.jpg);  left top no-repeat;width:48px; height:21px; }\r\n");
      out.write(".qd{border:none;background:url(pictures/lyqd.jpg);  left top no-repeat;width:48px; height:19px; }\r\n");
      out.write("\r\n");
      out.write(".STYLE2 {font-weight: bold}\r\n");
      out.write(".STYLE3 {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".STYLE5 {font-size: 12px}\r\n");
      out.write(".STYLE6 {\r\n");
      out.write("\tcolor: #0000FF;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write(".STYLE8 {\r\n");
      out.write("\tcolor: blue;\r\n");
      out.write("\tfont-family: \"幼圆\";\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("}\r\n");
      out.write(".area \r\n");
      out.write("{ border:1px solid #F90; overflow:auto; background:#fff url(pictures/sygb.jpg) right bottom no-repeat;color:#03C;font-size:14px}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\"> \r\n");
      out.write("   function showfb(){\r\n");
      out.write("      var x=document.getElementById(\"fb\");\r\n");
      out.write("\t  x.style.display=\"block\";\r\n");
      out.write("   }\r\n");
      out.write("   function disshowfb(){\r\n");
      out.write("      var x=document.getElementById(\"fb\");\r\n");
      out.write("\t  x.style.display=\"none\";\r\n");
      out.write("   }\r\n");
      out.write("   function showhf(i){\r\n");
      out.write("      var x=document.getElementById(i);\r\n");
      out.write("\t  x.style.display=\"block\";\r\n");
      out.write("   }\r\n");
      out.write("   function disshowhf(i){\r\n");
      out.write("      var x=document.getElementById(i);\r\n");
      out.write("\t  x.style.display=\"none\";\r\n");
      out.write("   }\r\n");
      out.write("   function showyd(){\r\n");
      out.write("      var x=document.getElementById(\"yd\");\r\n");
      out.write("\t  x.style.display=\"block\";\r\n");
      out.write("   }\r\n");
      out.write("   function denyyd(){\r\n");
      out.write("      var x=document.getElementById(\"yd\");\r\n");
      out.write("\t  x.style.display=\"none\";\r\n");
      out.write("   }\r\n");
      out.write("   function showmc(){\r\n");
      out.write("      var x=document.getElementById(\"mc\");\r\n");
      out.write("\t  x.style.display=\"block\";\r\n");
      out.write("   }\r\n");
      out.write("   function denymc(){\r\n");
      out.write("      var x=document.getElementById(\"mc\");\r\n");
      out.write("\t  x.style.display=\"none\";\r\n");
      out.write("   }\r\n");
      out.write("   function showms(){\r\n");
      out.write("      var x=document.getElementById(\"ms\");\r\n");
      out.write("\t  x.style.display=\"block\";\r\n");
      out.write("   }\r\n");
      out.write("   function denyms(){\r\n");
      out.write("      var x=document.getElementById(\"ms\");\r\n");
      out.write("\t  x.style.display=\"none\";\r\n");
      out.write("   }\r\n");
      out.write("   function framesize(){\r\n");
      out.write("\t  parent.document.getElementById(\"frame1\").style.height= document.body.scrollHeight;\r\n");
      out.write("\t  parent.document.getElementById(\"frame1\").style.width = 1349.5; \r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   var XMLHttpReq = false;\r\n");
      out.write("   \r\n");
      out.write("    function createXMLHttpRequest() {\r\n");
      out.write("\t\tif(window.XMLHttpRequest) { //Mozilla 浏览器\r\n");
      out.write("\t\t\tXMLHttpReq = new XMLHttpRequest();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if (window.ActiveXObject) { // IE浏览器\r\n");
      out.write("\t\t\ttry {\r\n");
      out.write("\t\t\t\tXMLHttpReq = new ActiveXObject(\"Msxml2.XMLHTTP\");\r\n");
      out.write("\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\tXMLHttpReq = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t\t\t} catch (e) {}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction sendRequest(url) {\r\n");
      out.write("\t\tcreateXMLHttpRequest();\r\n");
      out.write("\t\tXMLHttpReq.open(\"GET\", url, true);\r\n");
      out.write("\t\tXMLHttpReq.onreadystatechange = back;//指定响应函数\r\n");
      out.write("\t\tXMLHttpReq.send(null);  // 发送请求\r\n");
      out.write("\t}\r\n");
      out.write("\t// 处理返回信息函数\r\n");
      out.write("    function back() {\r\n");
      out.write("    \tif (XMLHttpReq.readyState == 4) { // 判断对象状态\r\n");
      out.write("        \tif (XMLHttpReq.status == 200) { // 信息已经成功返回，开始处理信息\r\n");
      out.write("            \tvar text=XMLHttpReq.responseText;\r\n");
      out.write("        \t    var mess=document.getElementById(\"mess\");\r\n");
      out.write("        \t    mess.innerHTML=\"<font color=red size='-1' face='幼圆'>&nbsp;&nbsp;&nbsp;删除成功</font>\";\r\n");
      out.write("                setTimeout(c1,2000);\r\n");
      out.write("            } \r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\t\r\n");
      out.write("\t  function c1(){\r\n");
      out.write("\t\t  var mess=document.getElementById(\"mess\");\r\n");
      out.write("\t\t  mess.innerHTML=\"\";\r\n");
      out.write("\t  }\r\n");
      out.write("       function del1(i,j,k){\r\n");
      out.write("    \tvar x=confirm(\"您确定要删除此信息？\");\r\n");
      out.write("    \tif(x==true){\r\n");
      out.write("    \t  var objDiv = document.getElementById(i);\r\n");
      out.write("\t      var vtables = objDiv.childNodes; \r\n");
      out.write("\t      if (vtables.length > 0)\r\n");
      out.write("\t        objDiv.removeChild(vtables[vtables.length - 1]);  \r\n");
      out.write("\t       sendRequest(\"SerHandlePicRes?tag=del1&picid=\"+j+\"&resid=\"+k);\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("   function del2(i,j,k){\r\n");
      out.write("    \tvar x=confirm(\"您确定要删除此信息？\");\r\n");
      out.write("    \tif(x==true){\r\n");
      out.write("    \t  var objDiv = document.getElementById(i);\r\n");
      out.write("\t      var vtables = objDiv.childNodes; \r\n");
      out.write("\t      if (vtables.length > 0)\r\n");
      out.write("\t        objDiv.removeChild(vtables[vtables.length - 1]);  \r\n");
      out.write("\t       sendRequest(\"SerHandlePicRes?tag=del1&picid=\"+j+\"&ressid=\"+k);\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"framesize()\">\r\n");
      out.write("<table width=\"70%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" >\r\n");
      out.write("  ");

     DBUtil db=new DBUtil();
     String albumid="";
     String picid=request.getParameter("picid");
     String sql="select * from qz.pic where picid='"+picid+"'";
     List<Map<String,Object>> list=db.queryToList(sql);
      Map<String, Object> map=list.get(0);
      String pic=map.get("PICSOURSE").toString();
      String picname=map.get("PICNAME").toString();
      String picsm=map.get("PICSM").toString();
      String pictime=map.get("PICTIME").toString();
      albumid=map.get("ALBUMID").toString();
  
      out.write("\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"25\" background=\"pictures/photo1.jpg\">\r\n");
      out.write("\t   <table width=\"100%\" height=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"18%\" height=\"16\" align=\"center\"><span class=\"STYLE1\">我的相册&gt; ");
      out.print(db.getPicName(albumid) );
      out.write(" </span></td>\r\n");
      out.write("    <td width=\"42%\" align=\"right\" class=\"STYLE1\">查看方式：</td>\r\n");
      out.write("    <td width=\"22%\">&nbsp;<a href=\"album4.jsp?albumid=");
      out.print(albumid );
      out.write("\" class=\"STYLE5\">照片墙</a>&nbsp; \r\n");
      out.write("       <a href=\"album3.jsp?picid=");
      out.print(db.getFirstPicId(albumid));
      out.write("\" class=\"STYLE5\">卡片</a>&nbsp; <a href=\"SerChaPic?albumid=");
      out.print(albumid );
      out.write("\" class=\"STYLE5\">普通</a>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td width=\"20%\"><a href=\"album1.jsp\" class=\"STYLE5\" >返回相册首页</a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("    <!--特效代码-->\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("\t<table width=\"100%\" height=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"><tr><td>\r\n");
      out.write("\t<div class=\"rollBox\">\r\n");
      out.write("     <div class=\"LeftBotton\" onmousedown=\"ISL_GoUp()\" onmouseup=\"ISL_StopUp()\" onmouseout=\"ISL_StopUp()\"></div>\r\n");
      out.write("     <div class=\"Cont\" id=\"ISL_Cont\">\r\n");
      out.write("      <div class=\"ScrCont\">\r\n");
      out.write("       <div id=\"List1\">\r\n");
      out.write("       ");

        String picid2="";
		String sql1="select * from qz.pic where albumid='"+albumid+"'";
        List<Map<String,Object>> list1=db.queryToList(sql1);
        for(int i=0;i<list1.size();i++){
        	Map<String,Object> map1=list1.get(i);
        	String id=map1.get("PICID").toString();
        	if(i==0){
        		picid2=id;
        	}
        	String picn=map1.get("PICSOURSE").toString();
       
      out.write("\r\n");
      out.write("        <!-- 图片列表 begin -->\r\n");
      out.write("         <div class=\"pic\">\r\n");
      out.write("          <a href=\"album3.jsp?picid=");
      out.print(id );
      out.write("\"><img src=\"");
      out.print(picn );
      out.write("\" width=\"90\" height=\"70\"/></a>\r\n");
      out.write("         </div>       \r\n");
      out.write("        <!-- 图片列表 end -->\r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("       </div>\r\n");
      out.write("       <div id=\"List2\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"RightBotton\" onmousedown=\"ISL_GoDown()\" onmouseup=\"ISL_StopDown()\" onmouseout=\"ISL_StopDown()\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\t<!--111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111-->\r\n");
      out.write("\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write(".rollBox{width:1000px;overflow:hidden;padding:12px 0 5px 6px;}\r\n");
      out.write(".rollBox .LeftBotton{height:52px;width:19px;background:url(pictures/scroll.jpg) no-repeat 11px 0;overflow:hidden;float:left;display:inline;margin:25px 0 0 0;cursor:pointer;}\r\n");
      out.write(".rollBox .RightBotton{height:52px;width:20px;background:url(pictures/scroll.jpg) no-repeat -8px 0;overflow:hidden;float:left;display:inline;margin:25px 0 0 0;cursor:pointer;}\r\n");
      out.write(".rollBox .Cont{width:92%;overflow:hidden;float:left;}\r\n");
      out.write(".rollBox .ScrCont{width:100000px;}\r\n");
      out.write(".rollBox .Cont .pic{width:132px;float:left;text-align:center;}\r\n");
      out.write(".rollBox .Cont .pic img{padding:4px;background:#fff;border:1px solid #ccc;display:block;margin:0 auto;}\r\n");
      out.write(".rollBox .Cont .pic p{line-height:26px;color:#505050;}\r\n");
      out.write(".rollBox .Cont a:link,.rollBox .Cont a:visited{color:#626466;text-decoration:none;}\r\n");
      out.write(".rollBox .Cont a:hover{color:#f00;text-decoration:underline;}\r\n");
      out.write(".rollBox #List1,.rollBox #List2{float:left;}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("<!--//--><![CDATA[//><!--\r\n");
      out.write("//图片滚动列表 mengjia 070816\r\n");
      out.write("var Speed = 2; //速度(毫秒)\r\n");
      out.write("var Space = 10; //每次移动(px)\r\n");
      out.write("var PageWidth = 528; //翻页宽度\r\n");
      out.write("var fill = 0; //整体移位\r\n");
      out.write("var MoveLock = false;\r\n");
      out.write("var MoveTimeObj;\r\n");
      out.write("var Comp = 0;\r\n");
      out.write("var AutoPlayObj = null;\r\n");
      out.write("GetObj(\"List2\").innerHTML = GetObj(\"List1\").innerHTML;\r\n");
      out.write("GetObj('ISL_Cont').scrollLeft = fill;\r\n");
      out.write("GetObj(\"ISL_Cont\").onmouseover = function(){clearInterval(AutoPlayObj);}\r\n");
      out.write("GetObj(\"ISL_Cont\").onmouseout = function(){AutoPlay();}\r\n");
      out.write("AutoPlay();\r\n");
      out.write("function GetObj(objName){if(document.getElementById){return eval('document.getElementById(\"'+objName+'\")')}else{return eval('document.all.'+objName)}}\r\n");
      out.write("function AutoPlay(){ //自动滚动\r\n");
      out.write(" clearInterval(AutoPlayObj);\r\n");
      out.write(" AutoPlayObj = setInterval('ISL_GoDown();ISL_StopDown();',2500); //间隔时间\r\n");
      out.write("}\r\n");
      out.write("function ISL_GoUp(){ //上翻开始\r\n");
      out.write(" if(MoveLock) return;\r\n");
      out.write(" clearInterval(AutoPlayObj);\r\n");
      out.write(" MoveLock = true;\r\n");
      out.write(" MoveTimeObj = setInterval('ISL_ScrUp();',Speed);\r\n");
      out.write("}\r\n");
      out.write("function ISL_StopUp(){ //上翻停止\r\n");
      out.write(" clearInterval(MoveTimeObj);\r\n");
      out.write(" if(GetObj('ISL_Cont').scrollLeft % PageWidth - fill != 0){\r\n");
      out.write("  Comp = fill - (GetObj('ISL_Cont').scrollLeft % PageWidth);\r\n");
      out.write("  CompScr();\r\n");
      out.write(" }else{\r\n");
      out.write("  MoveLock = false;\r\n");
      out.write(" }\r\n");
      out.write(" AutoPlay();\r\n");
      out.write("}\r\n");
      out.write("function ISL_ScrUp(){ //上翻动作\r\n");
      out.write(" if(GetObj('ISL_Cont').scrollLeft <= 0){GetObj('ISL_Cont').scrollLeft = GetObj('ISL_Cont').scrollLeft + GetObj('List1').offsetWidth}\r\n");
      out.write(" GetObj('ISL_Cont').scrollLeft -= Space ;\r\n");
      out.write("}\r\n");
      out.write("function ISL_GoDown(){ //下翻\r\n");
      out.write(" clearInterval(MoveTimeObj);\r\n");
      out.write(" if(MoveLock) return;\r\n");
      out.write(" clearInterval(AutoPlayObj);\r\n");
      out.write(" MoveLock = true;\r\n");
      out.write(" ISL_ScrDown();\r\n");
      out.write(" MoveTimeObj = setInterval('ISL_ScrDown()',Speed);\r\n");
      out.write("}\r\n");
      out.write("function ISL_StopDown(){ //下翻停止\r\n");
      out.write(" clearInterval(MoveTimeObj);\r\n");
      out.write(" if(GetObj('ISL_Cont').scrollLeft % PageWidth - fill != 0 ){\r\n");
      out.write("  Comp = PageWidth - GetObj('ISL_Cont').scrollLeft % PageWidth + fill;\r\n");
      out.write("  CompScr();\r\n");
      out.write(" }else{\r\n");
      out.write("  MoveLock = false;\r\n");
      out.write(" }\r\n");
      out.write(" AutoPlay();\r\n");
      out.write("}\r\n");
      out.write("function ISL_ScrDown(){ //下翻动作\r\n");
      out.write(" if(GetObj('ISL_Cont').scrollLeft >= GetObj('List1').scrollWidth){GetObj('ISL_Cont').scrollLeft = GetObj('ISL_Cont').scrollLeft - GetObj('List1').scrollWidth;}\r\n");
      out.write(" GetObj('ISL_Cont').scrollLeft += Space ;\r\n");
      out.write("}\r\n");
      out.write("function CompScr(){\r\n");
      out.write(" var num;\r\n");
      out.write(" if(Comp == 0){MoveLock = false;return;}\r\n");
      out.write(" if(Comp < 0){ //上翻\r\n");
      out.write("  if(Comp < -Space){\r\n");
      out.write("   Comp += Space;\r\n");
      out.write("   num = Space;\r\n");
      out.write("  }else{\r\n");
      out.write("   num = -Comp;\r\n");
      out.write("   Comp = 0;\r\n");
      out.write("  }\r\n");
      out.write("  GetObj('ISL_Cont').scrollLeft -= num;\r\n");
      out.write("  setTimeout('CompScr()',Speed);\r\n");
      out.write(" }else{ //下翻\r\n");
      out.write("  if(Comp > Space){\r\n");
      out.write("   Comp -= Space;\r\n");
      out.write("   num = Space;\r\n");
      out.write("  }else{\r\n");
      out.write("   num = Comp;\r\n");
      out.write("   Comp = 0;\r\n");
      out.write("  }\r\n");
      out.write("  GetObj('ISL_Cont').scrollLeft += num;\r\n");
      out.write("  setTimeout('CompScr()',Speed);\r\n");
      out.write(" }\r\n");
      out.write("}\r\n");
      out.write("//--><!]]>\r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!--111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111-->\r\n");
      out.write("\t</td></tr></table>\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("   <!--特效代码-->\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("\t<!--一个照片的遍历-->\r\n");
      out.write("\t  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"70%\"><!--照片的内容-->\r\n");
      out.write("\t    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"500\" align=\"left\"><img src=\"");
      out.print(pic );
      out.write("\" width=\"600\" height=\"650\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"26\" valign=\"bottom\"><span class=\"STYLE2\"><strong><a href=\"javascript:void(0)\" onclick=\"showfb()\">评论</a></strong></span>\r\n");
      out.write("    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span id=\"mess\"></span></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"10\" ><hr width=\"100%\" color=\"#9999FF\" size=\"2\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("    <td height=\"60\" >\r\n");
      out.write("\t<!--pinglunxunhuan-->\r\n");
      out.write("\t");

	   String sql3="select * from qz.picres where picid='"+picid+"' order by time desc";
	   List<Map<String,Object>> list3=db.queryToList(sql3);
	   for(int i=0;i<list3.size();i++){
		   Map<String,Object> map3=list3.get(i);
		   String a=map3.get("RESPERSON").toString();
		   String b=map3.get("RESCONTENT").toString();
		   String c=map3.get("TIME").toString();
		   String d=map3.get("PICRESID").toString();
		   UserBean u=new InitUser().getUser(a);
	
      out.write("\r\n");
      out.write("\t  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" background=\"pictures/grdzuo.jpg\" id=\"");
      out.print(i+100 );
      out.write("\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"9%\" rowspan=\"2\"><img src=\"");
      out.print(u.getUpicname() );
      out.write("\" width=\"50\" height=\"45\" /></td>\r\n");
      out.write("    <td  align=\"left\"><span class=\"STYLE3\">");
      out.print(u.getUsername() );
      out.write("</span></td>\r\n");
      out.write("    <td ><span class=\"STYLE5\">");
      out.print(c );
      out.write("</span>&nbsp;&nbsp;<a href=\"javascript:void(0)\" onclick=\"showhf(");
      out.print(i-100 );
      out.write(")\" class=\"STYLE5\">回复</a>\r\n");
      out.write("    ");

                 if(request.getSession().getAttribute("userid")==request.getSession().getAttribute("conid")){
      out.write("\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"del1(");
      out.print(i+100 );
      out.write(',');
      out.print(picid );
      out.write(',');
      out.print(d );
      out.write(")\" class=\"STYLE5\">删除</a>");
} 
      out.write("\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"10%\" height=\"29\" class=\"STYLE3\" align=\"left\">评论内容</td>\r\n");
      out.write("    <td width=\"81%\"><span class=\"STYLE5\">");
      out.print(b );
      out.write("</span></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("  <!--4444444444444444444444444444444444444444444444444444444444444444新加的内容-->\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td colspan=\"3\" height=\"55\">\r\n");
      out.write("         <table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td ><hr width=\"100%\" size=\"5\" color=\"#FFFFFF\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"50\"><table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"9%\">&nbsp;</td>\r\n");
      out.write("        <td width=\"91%\"><table width=\"100%\" height=\"24%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td height=\"17\">\r\n");
      out.write("\t\t\t<!--真正的循环-->\r\n");
      out.write("\t\t\t");

			String sql5="select * from qz.picress where picresid='"+d+"'";
	    	List<Map<String, Object>> list5=db.queryToList(sql5);
	    	for(int k=0;k<list5.size();k++){
	    		Map<String, Object> map5=list5.get(k);
	    		String r1=map5.get("PICRESSID").toString();
	    		String r2=map5.get("PICRESID").toString();
	    		String r3=map5.get("RESPERSON").toString();
	    		String r4=map5.get("RESCONTENT").toString();
	    		String r5=map5.get("TIME").toString();
	    		UserBean u1=new InitUser().getUser(r3);		
			
      out.write("\r\n");
      out.write("\t\t\t    <table width=\"100%\" height=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" id=\"");
      out.print(i*100+k*11 );
      out.write("\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=\"11%\" rowspan=\"2\"><img src=\"");
      out.print(u1.getUpicname() );
      out.write("\" width=\"50\" height=\"45\" /></td>\r\n");
      out.write("            <td width=\"11%\" height=\"21\"  align=\"left\"><span class=\"STYLE3\">");
      out.print(u1.getUsername() );
      out.write(" </span></td>\r\n");
      out.write("            <td width=\"78%\" ><span class=\"STYLE5\">");
      out.print(r5 );
      out.write("</span>&nbsp;&nbsp;\r\n");
      out.write("            ");

                 if(request.getSession().getAttribute("userid")==request.getSession().getAttribute("conid")){
      out.write("\r\n");
      out.write("            <a href=\"javascript:void(0)\" onclick=\"del2(");
      out.print(i*100+k*11 );
      out.write(',');
      out.print(picid );
      out.write(',');
      out.print(r1 );
      out.write(")\" class=\"STYLE5\">删除</a></td>");
} 
      out.write("\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td  class=\"STYLE3\" align=\"left\">回复内容</td>\r\n");
      out.write("            <td ><span class=\"STYLE5\">");
      out.print(r4 );
      out.write("</span></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("\t\t  <tr><td height=\"6\" colspan=\"3\"><hr width=\"100%\" size=\"4\" color=\"#FFFFFF\" /></td></tr>\r\n");
      out.write("        </table>\r\n");
      out.write("\t\t");
} 
      out.write("\t\r\n");
      out.write("\t\t\t<!--真正的循环-->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("\t\t\t<!--回复框-->\r\n");
      out.write("\t\t\t  <form action=\"SerHandlePicRes?tag=hf\" method=\"post\">\r\n");
      out.write("\t\t\t  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" id=\"");
      out.print(i-100 );
      out.write("\" style=\"display:none\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><textarea  name=\"content2\" cols=\"50\" rows=\"1\" class=\"area\"></textarea></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("      <input type=\"hidden\" name=\"picid\" value=\"");
      out.print(picid );
      out.write("\"/>\r\n");
      out.write("      <input type=\"hidden\" name=\"picresid\" value=\"");
      out.print(d );
      out.write("\"/>\r\n");
      out.write("\t  <input type=\"submit\" value=\"\" class=\"ch\" />&nbsp;<a href=\"javascript:void(0)\" class=\"STYLE5\" onclick=\"disshowhf(");
      out.print(i-100 );
      out.write(")\">取消</a>\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t<!--回复框-->\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("   <!--44444444444444444444444444444444444444444444444444444444444444444新加的内容-->\r\n");
      out.write("  <tr ><td colspan=\"3\" ><hr width=\"100%\" size=\"5\" color=\"#FFFFFF\" /></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("\t<!--pinglunxunhuan-->\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <form method=\"post\" action=\"SerHandlePicRes\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("      <textarea div=\"t\" name=\"content\" cols=\"50\" rows=\"1\" class=\"area\" onfocus=\"showfb()\"></textarea>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td valign=\"bottom\">\r\n");
      out.write("      <input type=\"hidden\" name=\"picid\" value=\"");
      out.print(picid );
      out.write("\"/>\r\n");
      out.write("      <div id=\"fb\" style=\"display:none\"><input type=\"submit\" value=\"\" class=\"ch\" />&nbsp;<a href=\"javascript:void(0)\" class=\"STYLE5\" onclick=\"disshowfb()\">取消</a></div>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"10\">\r\n");
      out.write("      &nbsp;\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  </form>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!--照片的内容-->\r\n");
      out.write("\t</td>\r\n");
      out.write("    <td width=\"30%\" align=\"left\" valign=\"top\" align=\"left\">\r\n");
      out.write("    <!-- youlan222222222222222222222222222222222222222222222222222222222222222222222 -->\r\n");
      out.write("    \r\n");
      out.write("    <table width=\"95%\" height=\"320\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"75\">&nbsp;</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"4\"><hr width=\"100%\" size=\"3\" color=\"#00ffff\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"60\"><!--11111111111111111111111111111111111111111111移动到-->\r\n");
      out.write("      <table width=\"100%\" height=\"40\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td width=\"67%\" height=\"20\" class=\"STYLE3\">所属相册：&nbsp;");
      out.print(db.getPicName(albumid) );
      out.write("</td>\r\n");
      out.write("          ");

                 if(request.getSession().getAttribute("userid")==request.getSession().getAttribute("conid")){
      out.write("\r\n");
      out.write("          <td width=\"33%\" height=\"20\"><a href=\"javascript:void(0)\" class=\"STYLE5\" onclick=\"showyd()\">移动到</a>\r\n");
      out.write("\t\t  &nbsp;<a href=\"SerHandlePic?tag=sethead&picsourse=");
      out.print(pic );
      out.write("&albumid=");
      out.print(albumid );
      out.write("&picid=");
      out.print(picid );
      out.write("\" class=\"STYLE5\" \">设首页</a></td>\r\n");
      out.write("          ");
} 
      out.write("\r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("          <tr>\r\n");
      out.write("            <td colspan=\"2\">\r\n");
      out.write("\t\t\t    <form action=\"SerHandlePic?tag=move\" method=\"post\">\r\n");
      out.write("\t\t\t    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" id=\"yd\" style=\"display:none\">\r\n");
      out.write("\t\t\t    <br/>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td width=\"50%\" height=\"30\"><select name=\"xc\" class=\"se\" style=\"width:150px\">\r\n");
      out.write("                      ");

                      String userid=request.getSession().getAttribute("userid").toString();
                      UserBean u=new InitUser().getUser(userid);
              List<Map<String, Object>> listt=u.getAlbums();
              for(int i=0;i<listt.size();i++){
            	  Map<String,Object> mapt=listt.get(i);
            	  String name=mapt.get("ALBUMNAME").toString();          
            
      out.write("\r\n");
      out.write("                      <option>");
      out.print(name );
      out.write("</option>\r\n");
      out.write("                     ");
} 
      out.write("\r\n");
      out.write("                  </select></td>\r\n");
      out.write("                  <input type=\"hidden\" name=\"picid\" value=\"");
      out.print(picid );
      out.write("\"/>\r\n");
      out.write("                  <input type=\"hidden\" name=\"albumid\" value=\"");
      out.print(albumid );
      out.write("\"/>\r\n");
      out.write("                  <td width=\"30%\">&nbsp;&nbsp;<input  type=\"submit\" class=\"qd\" value=\"\" />\r\n");
      out.write("                    &nbsp;</td>\r\n");
      out.write("                  <td width=\"20%\" valign=\"middle\">&nbsp;&nbsp;<a href=\"javascript:void(0)\" class=\"STYLE5\" onclick=\"denyyd()\">取消</a></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("\t\t\t</form></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        \r\n");
      out.write("      </table>\r\n");
      out.write("      <!--1111111111111111111111111111111111111111移动到--></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"4\"><hr width=\"100%\" size=\"3\" color=\"#00ffff\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"67\">\r\n");
      out.write("\t   <!--修改照片名-->\r\n");
      out.write("\t\r\n");
      out.write("\t   \t<table width=\"100%\" height=\"60\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("         <tr>\r\n");
      out.write("           <td width=\"67%\" height=\"20\" class=\"STYLE3\">照片名称：&nbsp;<font color=\"blue\">");
      out.print(picname );
      out.write("</font></td>\r\n");
      out.write("           ");

                 if(request.getSession().getAttribute("userid")==request.getSession().getAttribute("conid")){
      out.write("\r\n");
      out.write("           <td width=\"33%\" ><a href=\"javascript:void(0)\" class=\"STYLE5\" onclick=\"showmc()\">修改</a></td>");
} 
      out.write("\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("           <td height=\"40\" colspan=\"2\">\r\n");
      out.write("\t\t   <form action=\"SerHandlePic?tag=altername&picid=");
      out.print(picid );
      out.write("\" method=\"post\">\r\n");
      out.write("\t\t   <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" id=\"mc\" style=\"display:none\">\r\n");
      out.write("\t\t   <br/>\r\n");
      out.write("             <tr>\r\n");
      out.write("               <td height=\"25\"><input  value=\"");
      out.print(picname );
      out.write("\" type=\"text\" name=\"picname\" style=\"height:20px\" size=\"35\" class=\"te\"/></td>\r\n");
      out.write("             </tr>\r\n");
      out.write("             <tr>\r\n");
      out.write("               <td><input type=\"submit\" value=\"\" class=\"qd\" />&nbsp;<a href=\"javascript:void(0)\" class=\"STYLE5\" onclick=\"denymc()\">取消</a></td>\r\n");
      out.write("             </tr>\r\n");
      out.write("           </table>\r\n");
      out.write("\t\t   </form>\t\t   </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("       </table><!--修改照片名--></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"4\"><hr width=\"100%\" size=\"3\" color=\"#00ffff\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"60\" valign=\"top\">\r\n");
      out.write("\t   <!--照片描述-->\r\n");
      out.write("\t      <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"67%\" class=\"STYLE3\" height=\"20\">照片描述：</td>\r\n");
      out.write("    ");

                 if(request.getSession().getAttribute("userid")==request.getSession().getAttribute("conid")){
      out.write("\r\n");
      out.write("    <td width=\"33%\" ><a href=\"javascript:void(0)\" class=\"STYLE5\" onclick=\"showms()\">修改</a></td>");
} 
      out.write("\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td colspan=\"2\" height=\"20\"><span class=\"STYLE8\">");
      out.print(picsm );
      out.write("</span></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td colspan=\"2\">\r\n");
      out.write("\t<form action=\"SerHandlePic?tag=alterms&picid=");
      out.print(picid );
      out.write("\" method=\"post\">\r\n");
      out.write("\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" id=\"ms\" style=\"display:none\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td height=\"20\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t  <textarea name=\"picms\" cols=\"33\" rows=\"1\" class=\"area\">");
      out.print(picsm );
      out.write("</textarea>\t\t</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td><input type=\"submit\" value=\"\" class=\"qd\" />&nbsp;<a href=\"javascript:void(0)\" class=\"STYLE5\" onclick=\"denyms()\">取消</a></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("\t</form>\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\t   <!--照片描述-->\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"4\"><hr width=\"100%\" size=\"3\" color=\"#00ffff\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("\t   <table width=\"100%\" height=\"22\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"37%\" class=\"STYLE3\">上传时间：</td>\r\n");
      out.write("    <td width=\"63%\"><span class=\"STYLE6\">");
      out.print(pictime );
      out.write("</span> </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"4\"><hr width=\"100%\" size=\"3\" color=\"#00ffff\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  ");

                 if(request.getSession().getAttribute("userid")==request.getSession().getAttribute("conid")){
      out.write("\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"10\"><a href=\"SerHandlePic?tag=delone&picid=");
      out.print(picid );
      out.write("&albumid=");
      out.print(albumid );
      out.write("\" class=\"STYLE5\" \">删除该照片</a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"4\"><hr width=\"100%\" size=\"3\" color=\"#00ffff\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  ");
} 
      out.write("\r\n");
      out.write("  \r\n");
      out.write("</table>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- youlan222222222222222222222222222222222222222222222222222222222222222222222 -->\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("<!--一个照片的遍历-->\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
