package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.shxt.szqz.beans.*;
import com.shxt.szqz.database.*;
import com.shxt.szqz.listeners.*;

public final class centmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=gbk");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'centmain.jsp' starting page</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body { margin:0; background:url(pictures/bgmain.jpg)}\r\n");
      out.write(".areastyle1\r\n");
      out.write("{ border:1px solid #00ffff; overflow:auto; background:#fff  right bottom no-repeat;color:#03C;font-size:14px}\r\n");
      out.write(".style{\r\n");
      out.write("   font-size:13px;\r\n");
      out.write("   color:#CCCCCC;\r\n");
      out.write("   border-style:double;\r\n");
      out.write("}\r\n");
      out.write("a { text-decoration: none}\r\n");
      out.write("a:hover { text-decoration:underline;color:#666666}\r\n");
      out.write(".STYLE1 {\r\n");
      out.write("\tfont-family: \"幼圆\";\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("}\r\n");
      out.write(".STYLE111 {\r\n");
      out.write("\tfont-family: \"幼圆\";\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tcolor:blue;\r\n");
      out.write("}\r\n");
      out.write(".STYLE3 {\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-family: \"Courier New\", Courier, monospace;\r\n");
      out.write("\tcolor: #0033CC;\r\n");
      out.write("}\r\n");
      out.write(".photostyle{\r\n");
      out.write("   height:150px;\r\n");
      out.write("   width:130px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".STYLE5 {font-family: \"黑体\"}\r\n");
      out.write(".STYLE7 {\r\n");
      out.write("\tfont-family: \"幼圆\";\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("}\r\n");
      out.write(".STYLE8 {\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tcolor: #3333CC;\r\n");
      out.write("\tfont-family: \"幼圆\"; \r\n");
      out.write("}\r\n");
      out.write(".STYLE9 {\r\n");
      out.write("\tcolor: #000000;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write(".hf1{border:none;background:url(pictures/sayfb.jpg);  left top no-repeat;width:54px; height:21px; }\r\n");
      out.write(".hf{border:none;background:url(pictures/liuyan1.jpg);  left top no-repeat;width:71px; height:27px; }\r\n");
      out.write(".ch{border:none;background:url(pictures/sayfb.jpg);  left top no-repeat;width:54px; height:21px; }\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body,div,ul,li{\r\n");
      out.write(" margin:0 auto;\r\n");
      out.write(" padding:0;\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write(" font:12px \"宋体\";\r\n");
      out.write(" text-align:center;\r\n");
      out.write("}\r\n");
      out.write("a:link{\r\n");
      out.write(" color:#00F;\r\n");
      out.write(" text-decoration:none;\r\n");
      out.write("}\r\n");
      out.write("a:visited {\r\n");
      out.write(" color: #00F;\r\n");
      out.write(" text-decoration:none;\r\n");
      out.write("}\r\n");
      out.write("a:hover {\r\n");
      out.write(" color: #c00;\r\n");
      out.write(" text-decoration:underline;\r\n");
      out.write("}\r\n");
      out.write("ul{\r\n");
      out.write(" list-style:none;\r\n");
      out.write("}\r\n");
      out.write(".main{\r\n");
      out.write(" clear:both;\r\n");
      out.write(" padding:8px;\r\n");
      out.write(" text-align:center;\r\n");
      out.write("}\r\n");
      out.write("/*第一种形式*/\r\n");
      out.write("#tabs0 {\r\n");
      out.write(" height: auto;\r\n");
      out.write(" width: 600px;\r\n");
      out.write(" border: 1px solid #cbcbcb;\r\n");
      out.write(" background-color: #f2f6fb;\r\n");
      out.write("}\r\n");
      out.write(".menu0{\r\n");
      out.write(" width: 400px;\r\n");
      out.write(" float:left;\r\n");
      out.write("}\r\n");
      out.write(".menu0 li{\r\n");
      out.write(" display:block;\r\n");
      out.write(" float: left;\r\n");
      out.write(" padding: 4px 0;\r\n");
      out.write(" width:100px;\r\n");
      out.write(" text-align: center;\r\n");
      out.write(" cursor:pointer;\r\n");
      out.write(" background: #FFFFff;\r\n");
      out.write("}\r\n");
      out.write(".menu0 li.hover{\r\n");
      out.write(" background: #f2f6fb;\r\n");
      out.write("}\r\n");
      out.write("#main0 ul{\r\n");
      out.write(" display: none;\r\n");
      out.write("}\r\n");
      out.write("#main0 ul.block{\r\n");
      out.write(" display: block;\r\n");
      out.write("}\r\n");
      out.write(".STYLE1 {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".STYLE11 {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\r\n");
      out.write("\tcolor:blue;\r\n");
      out.write("}\r\n");
      out.write(".STYLE2 {font-size: 12px}\r\n");
      out.write(".STYLE16 {font-size: 12px; font-family: \"黑体\"; }\r\n");
      out.write(".STYLE17 {font-size: 16px; font-family: \"隶书\"; }\r\n");
      out.write(".STYLE18 {color: #9933FF}\r\n");
      out.write(".STYLE19 {font-size: 12px}\r\n");
      out.write("a { text-decoration: none}\r\n");
      out.write("a:hover { text-decoration:underline;color:#666666}\r\n");
      out.write(".area \r\n");
      out.write("{ border:1px solid #0033FF; overflow:auto; background:#fff url(pictures/sygb.jpg) right bottom no-repeat;color:#03C;font-size:14px}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("function showfk(){\r\n");
      out.write("\tvar x=document.getElementById(\"fk\");\r\n");
      out.write("    x.style.display=\"block\";\r\n");
      out.write("}\r\n");
      out.write("function showfr(){\r\n");
      out.write("\tvar x=document.getElementById(\"fr\");\r\n");
      out.write("    x.style.display=\"block\";\r\n");
      out.write("}\r\n");
      out.write("function disshowfk(){\r\n");
      out.write("\tvar x=document.getElementById(\"fk\");\r\n");
      out.write("    x.style.display=\"none\";\r\n");
      out.write("}\r\n");
      out.write("function disshowfr(){\r\n");
      out.write("\tvar x=document.getElementById(\"fr\");\r\n");
      out.write("    x.style.display=\"none\";\r\n");
      out.write("}\r\n");
      out.write("function nc1(i){\r\n");
      out.write("    var x=document.getElementById(i);\r\n");
      out.write("    x.style.display=\"block\";\r\n");
      out.write("}\r\n");
      out.write("function nc2(i){\r\n");
      out.write("    var x=document.getElementById(i);\r\n");
      out.write("    x.style.display=\"none\";\r\n");
      out.write("}\r\n");
      out.write("function show(i){\r\n");
      out.write("    var x=document.getElementById(i);\r\n");
      out.write("    x.style.display=\"block\";\r\n");
      out.write("}\r\n");
      out.write("function hide(i){\r\n");
      out.write("    var x=document.getElementById(i);\r\n");
      out.write("    x.style.display=\"none\";\r\n");
      out.write("}\r\n");
      out.write("function change1(){\r\n");
      out.write("  var x=document.getElementById(\"ly\");\r\n");
      out.write("  x.rows=\"3\";\r\n");
      out.write("  var x=document.getElementById(\"lyd\");\r\n");
      out.write("  x.style.display=\"block\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("  function change2(){\r\n");
      out.write("     var s=document.getElementById(\"ly\");\r\n");
      out.write("\t s.rows=\"2\";\r\n");
      out.write("\t var x=document.getElementById(\"lyd\");\r\n");
      out.write("\t x.style.display=\"none\";\r\n");
      out.write("  }\r\n");
      out.write("  function have1(i){\r\n");
      out.write("     var x=document.getElementById(i);\r\n");
      out.write("     x.style.display=\"block\";\r\n");
      out.write("  }\r\n");
      out.write("  function have11(i){\r\n");
      out.write("     var x=document.getElementById(i);\r\n");
      out.write("     x.style.display=\"none\";\r\n");
      out.write("  }\r\n");
      out.write("    function have2(i){\r\n");
      out.write("     var x=document.getElementById(i);\r\n");
      out.write("     x.style.display=\"block\";\r\n");
      out.write("  }\r\n");
      out.write("  function have22(i){\r\n");
      out.write("     var x=document.getElementById(i);\r\n");
      out.write("     x.style.display=\"none\";\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function change3(i,j){\r\n");
      out.write("  var x=document.getElementById(i);\r\n");
      out.write("  x.rows=\"2\";\r\n");
      out.write("  var x=document.getElementById(j);\r\n");
      out.write("  x.style.display=\"block\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("  function change4(i,j){\r\n");
      out.write("     var s=document.getElementById(i);\r\n");
      out.write("\t s.rows=\"1\";\r\n");
      out.write("\t var x=document.getElementById(j);\r\n");
      out.write("\t x.style.display=\"none\";\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function change5(i,j){\r\n");
      out.write("     var s=document.getElementById(i);\r\n");
      out.write("\t s.rows=\"2\";\r\n");
      out.write("\t var x=document.getElementById(j);\r\n");
      out.write("\t x.style.display=\"block\";\r\n");
      out.write("  }\r\n");
      out.write("  function change6(i,j){\r\n");
      out.write("     var s=document.getElementById(i);\r\n");
      out.write("\t s.rows=\"1\";\r\n");
      out.write("\t var x=document.getElementById(j);\r\n");
      out.write("\t x.style.display=\"none\";\r\n");
      out.write("  }\r\n");
      out.write("  function del1(i,j){\r\n");
      out.write("    \tvar x=confirm(\"您确定要删除此信息？\");\r\n");
      out.write("    \tif(x==true){\r\n");
      out.write("    \t  var objDiv = document.getElementById(i);\r\n");
      out.write("\t      var vtables = objDiv.childNodes; \r\n");
      out.write("\t      if (vtables.length > 0)\r\n");
      out.write("\t        objDiv.removeChild(vtables[vtables.length - 1]);  \r\n");
      out.write("\t       sendRequest(\"SerHandleSay?tag=del&sayid=\"+j);\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("   function del2(i,j){\r\n");
      out.write("    \tvar x=confirm(\"您确定要删除此信息？\");\r\n");
      out.write("    \tif(x==true){\r\n");
      out.write("    \t  var objDiv = document.getElementById(i);\r\n");
      out.write("\t      var vtables = objDiv.childNodes; \r\n");
      out.write("\t      if (vtables.length > 0)\r\n");
      out.write("\t        objDiv.removeChild(vtables[vtables.length - 1]);  \r\n");
      out.write("\t       sendRequest(\"SerHandleSay?tag=rdel&sayresid=\"+j);\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("function framesize(){\r\n");
      out.write("\t  parent.document.getElementById(\"frame1\").style.height= document.body.scrollHeight;\r\n");
      out.write("\t  parent.document.getElementById(\"frame1\").style.width = 1349.5; \r\n");
      out.write("   }\r\n");
      out.write("function show(i,j){\r\n");
      out.write("\tvar a=document.getElementById(j);\r\n");
      out.write("\t a.value=\"\";\r\n");
      out.write("     var x=document.getElementById(i);\r\n");
      out.write("\t x.style.display=\"block\";\r\n");
      out.write("  }\r\n");
      out.write("   function deny(i,j){\r\n");
      out.write("     var a=document.getElementById(j);\r\n");
      out.write("\t a.value=\"say something\";\r\n");
      out.write("     var x=document.getElementById(i);\r\n");
      out.write("\t x.style.display=\"none\";\r\n");
      out.write("  }\r\n");
      out.write("function setTab(m,n){\r\n");
      out.write(" var tli=document.getElementById(\"menu\"+m).getElementsByTagName(\"li\");\r\n");
      out.write(" var mli=document.getElementById(\"main\"+m).getElementsByTagName(\"ul\");\r\n");
      out.write(" for(i=0;i<tli.length;i++){\r\n");
      out.write("  tli[i].className=i==n?\"hover\":\"\";\r\n");
      out.write("  mli[i].style.display=i==n?\"block\":\"none\";\r\n");
      out.write(" }\r\n");
      out.write("}\r\n");
      out.write("function change1(){\r\n");
      out.write("  var x=document.getElementById(\"area\");\r\n");
      out.write("  x.rows=\"4\";\r\n");
      out.write("  x.innerHTML=\"\";\r\n");
      out.write("}\r\n");
      out.write("function change2(){\r\n");
      out.write("  var x=document.getElementById(\"area\");\r\n");
      out.write("  x.rows=\"2\";\r\n");
      out.write("  x.innerHTML=\"留个言,表示一下关心\";\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write(" function showxc(i,j){\r\n");
      out.write("     var x=document.getElementById(i);\r\n");
      out.write("\t x.style.display=\"block\";\r\n");
      out.write("\t var a=document.getElementById(j);\r\n");
      out.write("\t a.value=\"\";\r\n");
      out.write("  }\r\n");
      out.write("   function denyxc(i,j){\r\n");
      out.write("     var a=document.getElementById(j);\r\n");
      out.write("\t a.value=\"say something\";\r\n");
      out.write("     var x=document.getElementById(i);\r\n");
      out.write("\t x.style.display=\"none\";\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"framesize()\">\r\n");
      out.write("<table width=\"75%\" height=auto border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n");
      out.write("  <tr>\r\n");
      out.write("  ");
 
   int grade=1;
   int pagey=4;
   String pp=request.getParameter("atag");
   if(pp!=null){
	   pagey=Integer.parseInt(pp);
   }
   String userid="";
   UserBean u=null;
   userid=request.getSession().getAttribute("userid").toString();
   u=new InitUser().getUser(userid);
   DBUtil db=new DBUtil();
   grade=Integer.parseInt(u.getCount());

      out.write("\r\n");
      out.write("    <td width=\"18%\" valign=\"top\" bgcolor=\"#EEDDFF\" height=auto><table width=\"100%\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"75%\" ><div align=\"center\"><img src=\"");
      out.print(u.getUpicname() );
      out.write("\" class=\"photostyle\" /></div></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td height=\"49\" valign=\"bottom\" align=\"center\"><table width=\"75%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"20\" align=\"center\"><span class=\"STYLE3\"><a href=\"SerShowLoge\" target=\"frame1\">");
      out.print(u.getLog() );
      out.write("</a></span></td>\r\n");
      out.write("                <td align=\"center\" class=\"STYLE3\"><a href=\"album1.jsp\" target=\"frame1\">");
      out.print(u.getPhoto() );
      out.write("</a></td>\r\n");
      out.write("                <td align=\"center\" class=\"STYLE3\"><a href=\"SerShowSay\" target=\"frame1\">");
      out.print(u.getSay() );
      out.write("</a></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td><div align=\"center\" class=\"STYLE1\">日志</div></td>\r\n");
      out.write("                <td><div align=\"center\" class=\"STYLE1\">照片</div></td>\r\n");
      out.write("                <td><div align=\"center\" class=\"STYLE1\">说说</div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td><hr width=\"68%\" align=\"center\" color=\"yellow\" size=\"1\"/></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <td><table width=\"75%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"35%\"><div align=\"center\" class=\"STYLE11\">&nbsp;等级：</div></td>\r\n");
      out.write("                <td width=\"65%\">\r\n");
      out.write("                ");
 
                  if(grade<3){
                	  out.print("<img src='pictures/starr.png'/>");
                  }else if(grade<7){
                	  out.print("<img src='pictures/starr.png'/><img src='pictures/starr.png'/><img src='pictures/starr.png'/>");
                  }else if(grade<12){
                	  out.print("<img src='pictures/moon.png'/><img src='pictures/starr.png'/><img src='pictures/starr.png'/>");
                  }else{
                	  out.print("<img src='pictures/moon.png'/><img src='pictures/moon.png'/><img src='pictures/starr.png'/><img src='pictures/starr.png'/>");
                  }
  
                
                
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("              </tr>\r\n");
      out.write("         \r\n");
      out.write("         </table>\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td><hr width=\"68%\" align=\"center\" color=\"yellow\" size=\"1\"/></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td ><!-- 在线用户2222222222222222222222222222222222222222222222222222222222222222222222222222 -->\r\n");
      out.write("            <table width=\"100%\" height=\"auto\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("            <br/><br/>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td><div align=\"center\" class=\"STYLE1\">在线好友</div><br/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td align=\"center\" valign=\"top\"><!--yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy-->\r\n");
      out.write("\t\t\t\t      \r\n");
      out.write("\t\t\t\t        <!-- 图片列表 begin -->\r\n");
      out.write("\t\t\t\t        ");

				        Map<String,String> mapline=GetOnLineListener.getMap();
				        Set<String> set=mapline.keySet();
				        Iterator<String> it=set.iterator();
				        while(it.hasNext()){
				            String id=mapline.get(it.next());
				            UserBean u6=new InitUser().getUser(id);
				        
      out.write("\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t <img src=\"");
      out.print(u6.getUpicname() );
      out.write("\" width=\"70\" height=\"55\"/>\r\n");
      out.write("\t\t\t\t         <p><a href=\"javascript:void(0)\"><font size=\"-1\">");
      out.print(u6.getUsername() );
      out.write("</font></a></p>\r\n");
      out.write("\t\t\t\t      \r\n");
      out.write("\t\t\t\t          \r\n");
      out.write("\t\t\t\t        <!-- 图片列表 end -->\r\n");
      out.write("\t\t\t\t        \r\n");
      out.write("\t\t\t\t       \r\n");
      out.write("                     ");
} 
      out.write("\r\n");
      out.write("              <!--yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy-->\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- 在线用户22222222222222222222222222222222222222222222222222222222222222 -->\r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      \r\n");
      out.write("      <tr>\r\n");
      out.write("        <td ><!-- 在线用户2222222222222222222222222222222222222222222222222222222222222222222222222222 -->\r\n");
      out.write("            <table width=\"100%\" height=\"auto\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("            <br/><br/>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td><div align=\"center\" class=\"STYLE1\"><a href=\"javascript:void(0)\" ondblclick=\"showfk()\" onclick=\"disshowfk()\" >最近访客</a></div><br/></td>\r\n");
      out.write("              \r\n");
      out.write("            </tr>\r\n");
      out.write("        \r\n");
      out.write("            <tr >\r\n");
      out.write("              ");

                 if(request.getSession().getAttribute("userid")!=request.getSession().getAttribute("conid")){
      out.write("\r\n");
      out.write("              <p align=\"center\"><a href=\"javascript:void(0)\"><font size=\"-1\">清除本次访问记录</font></a> <hr width=\"65%\" align=\"center\" color=\"yellow\" size=\"1\"/></p>\r\n");
      out.write("         \r\n");
      out.write("             \r\n");
      out.write("      ");
} 
      out.write("\r\n");
      out.write("              \r\n");
      out.write("              <td align=\"center\" valign=\"top\" id=\"fk\" style=\"display:none\"><!--yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy-->\r\n");
      out.write("\t\t\t\t      \r\n");
      out.write("\t\t\t\t        <!-- 图片列表 begin -->\r\n");
      out.write("\t\t\t\t        ");

				        List<Map<String, Object>> listfk=u.getFK();
				        for(int fk=0;fk<listfk.size();fk++){
				        	Map<String, Object> mapfk=listfk.get(fk);
				        	String guest=mapfk.get("GUEST").toString();
				        	UserBean ufk=new InitUser().getUser(guest);
				        	String time=mapfk.get("TIME").toString().substring(5,19);
				        
				        
      out.write("\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t <img src=\"");
      out.print(ufk.getUpicname() );
      out.write("\" width=\"70\" height=\"55\"/>\r\n");
      out.write("\t\t\t\t\t\t ");

                 if(request.getSession().getAttribute("userid")==request.getSession().getAttribute("conid")){
      out.write("\r\n");
      out.write("\t\t\t\t         <p><a href=\"SerMakeFriends?fri2=");
      out.print(guest );
      out.write("&tag=changeqz\" target=\"_top\"><font size=\"-1\">");
      out.print(ufk.getUsername() );
      out.write("</font></a></p>\r\n");
      out.write("\t\t\t\t         ");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t         <p><font size=\"-1\">");
      out.print(ufk.getUsername() );
      out.write("</font></p>\r\n");
      out.write("\t\t\t\t         ");
} 
      out.write("\r\n");
      out.write("\t                     <p class=\"STYLE111\">");
      out.print(time );
      out.write("</p>\r\n");
      out.write("\t\t\t\t        <!-- 图片列表 end -->\r\n");
      out.write("                     ");
} 
      out.write("\r\n");
      out.write("              <!--yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy-->\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            </div>\r\n");
      out.write("        </table>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- 在线用户22222222222222222222222222222222222222222222222222222222222222 -->\r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("\t\r\n");
      out.write("    <td width=\"62%\" valign=\"top\" height=\"auto\" bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"60\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td width=\"49%\"><div align=\"left\"><span class=\"STYLE7\">&nbsp;&nbsp; ");
      out.print(u.getUsername() );
      out.write("</span></div></td>\r\n");
      out.write("          <td width=\"49%\">\r\n");
      out.write("             ");

                 if(request.getSession().getAttribute("userid")==request.getSession().getAttribute("conid")){
      out.write("\r\n");
      out.write("             <div align=\"right\"><span class=\"STYLE7\"><a href=\"grd.jsp\"><img src=\"pictures/alterper.jpg\" width=\"93\" height=\"24\"/></a></span></div>\r\n");
      out.write("          ");
} 
      out.write("\r\n");
      out.write("          </td>\r\n");
      out.write("          <td width=\"2%\"> </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"43\">\r\n");
      out.write("      \r\n");
      out.write("      \t    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"10%\" align=\"right\"><span class=\"STYLE8\">账号：</span></td>\r\n");
      out.write("    <td width=\"14%\" align=\"center\"><span class=\"STYLE9\">");
      out.print(u.getUserid() );
      out.write("</span></td>\r\n");
      out.write("    <td width=\"7%\" align=\"right\" class=\"STYLE8\">家乡：</td>\r\n");
      out.write("    <td width=\"19%\" align=\"center\"><span class=\"STYLE9\">");
      out.print(u.getHome() );
      out.write("</span></td>\r\n");
      out.write("    <td width=\"8%\" align=\"right\" class=\"STYLE8\">生日：</td>\r\n");
      out.write("    <td width=\"21%\" align=\"center\"><span class=\"STYLE9\">");
      out.print(u.getBirth() );
      out.write("</span></td>\r\n");
      out.write("    <td width=\"7%\" align=\"right\" class=\"STYLE8\">星座：</td>\r\n");
      out.write("\t<td width=\"14%\" align=\"center\"><span class=\"STYLE9\">水瓶座</span></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("     </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <form method=\"post\" action=\"SerHandleLy?tag=addly\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"60\" align=\"center\">\r\n");
      out.write("\t<textarea name=\"mainarea\"  cols=\"80\" rows=\"2\" class=\"style\" name=\"area\" id=\"area\" onfocus=\"change1()\" > 留个言，表示一下关心吧    </textarea>\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("\t\t\t  <table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t  <tr><td height=\"23\">&nbsp;</td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t\t<td><div align=\"right\" id=\"fb\" ><input type=\"submit\" value=\"\" class=\"hf\"/></div></td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t</table>\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  </form>\r\n");
      out.write("  <tr>\r\n");
      out.write("     <td height=\"10px\"><hr align=\"center\" width=\"95%\" size=\"2\" color=\"#0066FF\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("     <td><div id=\"tabs0\">\r\n");
      out.write(" <ul class=\"menu0\" id=\"menu0\">\r\n");
      out.write("  <li onclick=\"setTab(0,0)\" class=\"hover\"><font size=\"+1\" color=\"black\" face=\"隶书\">好友动态</font></li>\r\n");
      out.write("  <li onclick=\"setTab(0,1)\"><font size=\"+1\" color=\"black\" face=\"隶书\">评论回复</font></li>\r\n");
      out.write("  <li onclick=\"setTab(0,2)\"><font size=\"+1\" color=\"black\" face=\"隶书\">好友说说</font></li>\r\n");
      out.write(" </ul>\r\n");
      out.write(" <div class=\"main\" id=\"main0\">\r\n");
      out.write("  <ul class=\"block\" ><li><!-- rizhi9999999999999999999999999999999999999999999999999999999999999999999999999999999999 -->\r\n");
      out.write("      <!--日志模块的设计-->\r\n");
      out.write("      ");

         List<Map<String, Object>> listlog=null;
         int aa=0;
         if(request.getSession().getAttribute("userid")==request.getSession().getAttribute("conid")){
        	 listlog=u.getFriLog(userid);
         }else{
        	 listlog=u.getFriLog1(userid);
         }
            	 
         if(listlog!=null){
        	 aa=listlog.size();
        	 if(aa>pagey){
        		 aa=pagey;
        	 }
         }
         for(int i=0;i<aa;i++){
        	 Map<String, Object> mapp=listlog.get(i);
        	 String a=mapp.get("LOGID").toString();
        	 String b=mapp.get("USERID").toString();
        	 String c=mapp.get("LOGTOPIC").toString();
        	 String d=mapp.get("LOGCONTENT").toString().substring(0,10);
        	 String e=mapp.get("LOGTIME").toString();
        	 String f=mapp.get("TYPE").toString();
        	 
        	 String g=mapp.get("LOGFROM").toString();
        	 UserBean u1=new InitUser().getUser(b);
        	 

      
      out.write("\r\n");
      out.write("         <table width=\"100%\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><hr width=\"100%\" size=\"2\" color=\"#9933FF\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><table width=\"100%\" height=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"15%\" valign=\"top\" align=\"center\"><!--发表日志人呢的图像--><img src=\"");
      out.print(u1.getUpicname() );
      out.write("\" width=\"65\" height=\"58\" /></td>\r\n");
      out.write("        <td width=\"85%\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td height=\"26\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"16%\" align=\"left\"><span class=\"STYLE1\">");
      out.print(u1.getUsername() );
      out.write("</span></td>\r\n");
      out.write("                ");
if(f.equals("0")) {
      out.write("\r\n");
      out.write("                <td width=\"29%\" class=\"STYLE2\" align=\"left\">发表了日志</td>\r\n");
      out.write("                ");
}else{ 
      out.write("\r\n");
      out.write("                <td width=\"29%\" class=\"STYLE2\" align=\"left\">转载 <strong>");
      out.print(db.getUsername(g) );
      out.write("</strong> 的日志</td>\r\n");
      out.write("                \r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("                <td width=\"30%\" class=\"STYLE1\" align=\"left\">《<a href=\"SerHandleLog?tag=plfirst&logid=");
      out.print(a );
      out.write('"');
      out.write('>');
      out.print(c );
      out.write("</a>》</td>\r\n");
      out.write("\t\t\t\t<td width=\"25%\"><span class=\"STYLE2\" align=\"left\">");
      out.print(e );
      out.write("</span> </td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td align=\"left\"><span class=\"STYLE2\">");
      out.print(d );
      out.write("</span></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td><!--动态的循环-->\r\n");
      out.write("            ");

              DBUtil db1=new DBUtil();
              String sql2="select * from qz.comments where logid='"+a+"'  order by comid desc";
              List<Map<String,Object>> listcom=db1.queryToList(sql2);
              for(int ii=0;ii<listcom.size();ii++){
            	  Map<String,Object> mapcom=listcom.get(ii);
            	  String c1=mapcom.get("COMPERSON").toString();
            	  String c2=mapcom.get("COMCONTENT").toString();
            	  String c3=mapcom.get("COMTIME").toString();
            	  UserBean u3=new InitUser().getUser(c1);
             
            
            
      out.write("\r\n");
      out.write("\t\t\t   <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><hr width=\"100%\" size=\"2\" color=\"#00FFFF\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("\t   <!--图像和评论内容-->\r\n");
      out.write("           <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"14%\" valign=\"top\" align=\"center\"><!--评论人的图像--><img src=\"");
      out.print(u3.getUpicname() );
      out.write("\" width=\"50\" height=\"45\" /></td>\r\n");
      out.write("    <td width=\"86%\">\r\n");
      out.write("\t<!--评论内容-->\r\n");
      out.write("\t<table width=\"100%\" height=\"42\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"18%\"  class=\"STYLE1\">");
      out.print(u3.getUsername() );
      out.write("</td>\r\n");
      out.write("        <td width=\"82%\" align=\"left\" ><span class=\"STYLE2\" >");
      out.print(c3 );
      out.write("</span> </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td class=\"STYLE1\">评论内容</td>\r\n");
      out.write("        <td align=\"left\"><span class=\"STYLE2\">");
      out.print(c2 );
      out.write("</span></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("\t<!--评论内容--></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\t   <!--图像和评论内容-->\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\t");
} 
      out.write("\t\t  \r\n");
      out.write("\t\t\t<!--动态的循环-->\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("\t\t\t<!--回复组件-->\r\n");
      out.write("\t\t\t<form  method=\"post\" action=\"SerHandleCom?tag=hfs\">\r\n");
      out.write("\t\t\t<hr width=\"100%\" size=\"2\" color=\"#FFFFFF\" />\r\n");
      out.write("\t\t\t   <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" >\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td align=\"left\">\r\n");
      out.write("      <input type=\"hidden\" name=\"logid\" value=\"");
      out.print(a);
      out.write("\"/>\r\n");
      out.write("      <textarea name=\"area\" id=\"");
      out.print(i+3000 );
      out.write("\" class=\"area\" cols=\"50\" rows=\"1\" style=\"height:20px\" onfocus=\"show(");
      out.print(i+2000 );
      out.write(',');
      out.print(i+3000 );
      out.write(")\">say something</textarea>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr id=\"");
      out.print(i+2000 );
      out.write("\" style=\"display:none\" align=\"left\">\r\n");
      out.write("    <td ><input name=\"submit\" type=\"submit\" class=\"ch\" value=\"\" />&nbsp;\r\n");
      out.write("\t<a href=\"javascript:void(0)\" class=\"STYLE2\" onclick=\"deny(");
      out.print(i+2000 );
      out.write(',');
      out.print(i+3000 );
      out.write(")\">取消</a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!--回复组件-->\r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("      <!--日志模块的设计-->\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  ");
} 
      out.write("\r\n");
      out.write("  </li></ul><!-- rizhi9999999999999999999999999999999999999999999999999999999999999999999999999999999999 -->\r\n");
      out.write("  <ul class=\"block\"><li>\r\n");
      out.write("  <!-- xc999999999999999999999999999999999999999999999999999999999999999999999999999999999966666666666666666666666666666 -->\r\n");
      out.write("    ");
 
       int bb=0;
       List<Map<String, Object>> listpc=null;
       DBUtil db2=new DBUtil();
       if(request.getSession().getAttribute("userid")==request.getSession().getAttribute("conid")){
    	   listpc=db2.getFriAutoPic(userid);
       }else{
    	   listpc=db2.getFriAutoPic1(userid);
       }
       
       if(listpc!=null){
    	   bb=listpc.size();
    	   if(bb>pagey){
    		   bb=pagey;
    	   }
       }
       for(int i=0;i<bb;i++){
    	   Map<String, Object> mappc=listpc.get(i);
    	   String p1=mappc.get("PICID").toString();
    	   String p2=mappc.get("PICSOURSE").toString();
    	   String p3=mappc.get("PICNAME").toString();
    	   String p4=mappc.get("PICTIME").toString();
    	   String p5=db.getAlbumName(p1);
       	   String p6=db.getPicUser(p1);
       	   UserBean u6=new InitUser().getUser(p6);
      
    
      out.write("\r\n");
      out.write("    <table width=\"100%\" height=\"auto\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><hr width=\"100%\" size=\"2\" color=\"#99CCFF\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <!--左右2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222-->\r\n");
      out.write("    <td><table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"18%\" valign=\"top\" align=\"center\"><!--照片所属人图--><img src=\"");
      out.print(u6.getUpicname() );
      out.write("\" width=\"80\" height=\"70\" /></td>\r\n");
      out.write("\t\t<!--右侧部分3333333333333333333333333333333333333333333333333333333333333333333333333333-->\r\n");
      out.write("        <td width=\"82%\"><table width=\"100%\" height=\"39%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td height=\"19\"><!--zuoshang-->\r\n");
      out.write("\t\t\t   <table width=\"100%\" height=\"27\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"16%\" class=\"STYLE1\">");
      out.print(u6.getUsername() );
      out.write("</td>\r\n");
      out.write("    <td width=\"10%\" class=\"STYLE1\">的照片</td>\r\n");
      out.write("    <td width=\"15%\" align=\"center\"><span class=\"STYLE18 STYLE19\">");
      out.print(p3 );
      out.write("</span></td>\r\n");
      out.write("    <td width=\"30%\" align=\"left\"><span class=\"STYLE18 STYLE19\">来自相册《");
      out.print(p5 );
      out.write("》</span></td>\r\n");
      out.write("    <td width=\"29%\" align=\"left\"><span class=\"STYLE17\">的评论</span></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr><td height=\"8\" colspan=\"4\"><hr width=\"100%\" size=\"2\" color=\"#FF00FF\" /></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!--zuoshang-->\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td height=\"224\" valign=\"middle\" align=\"left\"><!--照片内容--><img src=\"");
      out.print(p2 );
      out.write("\" width=\"324\" height=\"258\" /></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td height=\"10\" align=\"left\"><span class=\"STYLE16\">");
      out.print(p4 );
      out.write(" 评论（");
      out.print(db.getPicResSum(p1) );
      out.write("）</span> </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("            <td><hr width=\"100%\" size=\"2\" color=\"#FF00FF\" /></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("            <td height=\"50\"><!--评论内容回复组件循环-->\r\n");
      out.write("            \r\n");
      out.write("\t\t\t   <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"28\">\r\n");
      out.write("\t<!--真正一条回复的内容循环-->\r\n");
      out.write("\t");
      
	        String sqlpcress="select * from qz.picres where picid='"+p1+"'";
            List<Map<String, Object>> listpcres=db.queryToList(sqlpcress);
            for(int f=0;f<listpcres.size();f++){
            	Map<String, Object> mapres=listpcres.get(f);
            	String re1=mapres.get("RESPERSON").toString();
            	String re2=mapres.get("RESCONTENT").toString();
            	String re3=mapres.get("TIME").toString();
            	UserBean u7=new InitUser().getUser(re1);
           
            
      out.write("\r\n");
      out.write("\t    <table width=\"100%\" height=\"50\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"12%\" rowspan=\"2\" valign=\"middle\" align=\"center\"><!--回复人图像--><img src=\"");
      out.print(u7.getUpicname() );
      out.write("\" width=\"43\" height=\"37\" /></td>\r\n");
      out.write("    <td width=\"20%\" height=\"22\" align=\"left\"><span class=\"STYLE1\">");
      out.print(u7.getUsername() );
      out.write("</span></td>\r\n");
      out.write("    <td width=\"68%\" class=\"STYLE17\" align=\"left\">");
      out.print(re2 );
      out.write("</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td colspan=\"2\" class=\"STYLE16\" align=\"left\">");
      out.print(re3 );
      out.write("&nbsp; 评论</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr><td colspan=\"3\"><hr width=\"100%\" size=\"1\" color=\"#999999\" /></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("     \r\n");
} 
      out.write("\t\r\n");
      out.write("\t   \r\n");
      out.write("\t<!--真正一条回复的内容循环-->\r\n");
      out.write("\t\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"26\"><!--回复组件-->\r\n");
      out.write("\t   <form method=\"post\" action=\"SerHandlePicRes?tag=qz\">\r\n");
      out.write("\t\t\t<hr width=\"100%\" size=\"2\" color=\"#FFFFFF\" />\r\n");
      out.write("\t\t\t   <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" >\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td align=\"left\">\r\n");
      out.write("      <input type=\"hidden\" name=\"picid\" value=\"");
      out.print(p1 );
      out.write("\"/>\r\n");
      out.write("      <textarea name=\"content\" id=\"");
      out.print(i-3000 );
      out.write("\" class=\"area\" cols=\"50\" rows=\"1\" style=\"height:20px\" onfocus=\"showxc(");
      out.print(i-2000 );
      out.write(',');
      out.print(i-3000 );
      out.write(")\">say something</textarea>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr id=\"");
      out.print(i-2000 );
      out.write("\" style=\"display:none\" align=\"left\">\r\n");
      out.write("    <td ><input name=\"submit\" type=\"submit\" class=\"ch\" value=\"\" />&nbsp;\r\n");
      out.write("\t<a href=\"javascript:void(0)\" class=\"STYLE2\" onclick=\"denyxc(");
      out.print(i-2000 );
      out.write(',');
      out.print(i-3000 );
      out.write(")\">取消</a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\t<!--回复组件-->\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<!--评论内容回复组件循环-->\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("        <!--右侧部分3333333333333333333333333333333333333333333333333333333333333333333333333333-->\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("\t <!--左右2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222-->\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("  ");
} 
      out.write("\r\n");
      out.write("  <!-- xc999999999999999999999999999999999999999999999999999999999999999999999999999999999966666666666666666666666666666 -->\r\n");
      out.write("  \r\n");
      out.write("  </li></ul>\r\n");
      out.write("  <ul class=\"block\"><li>\r\n");
      out.write("    <!-- 111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111 -->\r\n");
      out.write("      ");

                    String sqlss="";
                    int ll=0;
                    if(request.getSession().getAttribute("userid")==request.getSession().getAttribute("conid")){
                        sqlss="select * from qz.says where host in (select fri2 from qz.friends where fri1='"+userid+"' and state in(1,3)) order by saytime desc";
                    }else{
                    	sqlss="select * from qz.says where host='"+userid+"' order by saytime desc";
                    }
                    List<Map<String, Object>> listss=db.queryToList(sqlss);
                    String sayid="",b="",bbb="",c="",cc="",d="",e="";
                    if(listss!=null){
                    	ll=listss.size();
                    	if(ll>pagey){
                    		ll=pagey;
                    	}
                    }
                    for(int i=0;i<ll;i++){
            			Map<String, Object> map=listss.get(i);
            			sayid=map.get("SAYID").toString();
            			b=map.get("HOST").toString();
            			bbb=db.getUsername(b);
            			c=map.get("SAYPERSON").toString();
            			cc=db.getUsername(c);
            			d=map.get("SAYCONTENT").toString();
            			e=map.get("SAYTIME").toString();	
            			u=new InitUser().getUser(b);
                    
      out.write(" \r\n");
      out.write("                         <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" id=\"");
      out.print(i-3012 );
      out.write("\">\r\n");
      out.write("                           <tr>\r\n");
      out.write("                             <td width=\"15%\" height=\"79\" valign=\"top\" align=\"center\"><img src=\"");
      out.print(u.getUpicname() );
      out.write("\" width=\"60\" height=\"60\" /></td>\r\n");
      out.write("                             <td width=\"85%\"><!--正文-->\r\n");
      out.write("                                 <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                                   <tr>\r\n");
      out.write("                                     <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                                         <tr onmouseover=\"have1(");
      out.print(i+1000 );
      out.write(")\" onmouseout=\"have11(");
      out.print(i+1000 );
      out.write(")\">\r\n");
      out.write("                                           <td width=\"17%\" height=\"22\"><span class=\"STYLE1\">");
      out.print(bbb );
      out.write("</span></td>\r\n");
      out.write("                                           <td width=\"60%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t         <span class=\"STYLE16\">");
      out.print(e );
      out.write("</span>\t\t\t\t\t\t\t\t\t\t                                            </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   <td width=\"23%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t   <div id=\"");
      out.print(i+1000 );
      out.write("\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t   <a href=\"javascript:void(0)\" class=\"STYLE2\" onclick=\"change3(");
      out.print(i );
      out.write(',');
      out.print(i-100 );
      out.write(")\">回复</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t   <input type=\"hidden\" value=\"");
      out.print(sayid );
      out.write("\" id=\"is\">\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t   </div>\t\t\t\t\t\t\t\t           </td>\r\n");
      out.write("                                         </tr>\r\n");
      out.write("                                     </table></td>\r\n");
      out.write("                                   </tr>\r\n");
      out.write("                                   <tr>\r\n");
      out.write("                                     <td ><span class=\"STYLE17\"><br/>\r\n");
      out.write("                                     ");
      out.print(d );
      out.write("</span></td>\r\n");
      out.write("                                   </tr>\r\n");
      out.write("                                   <tr>\r\n");
      out.write("                                     <td><hr width=\"98%\" color=\"#666666\" size=\"2\" align=\"left\" /></td>\r\n");
      out.write("                                   </tr>\r\n");
      out.write("                                   <tr>\r\n");
      out.write("                                     <td><!--hufu-->\r\n");
      out.write("                                     ");
 
									    String sql1="select * from qz.sayres where sayid=? order by restime asc";
										Object obj1[]={sayid};
										List<Map<String, Object>> list1=db.queryToList(sql1, obj1);
										String r1="",r2="",r3="",r33="",r4="",r5="";
										for(int j=0;j<list1.size();j++){
											Map<String, Object> map1=list1.get(j);
											r1=map1.get("SAYRESID").toString();
											r2=map1.get("SAYID").toString();
											r3=map1.get("RESPERSON").toString();
											r33=db.getUsername(r3);
											r4=map1.get("RESTIME").toString();
											r5=map1.get("RESCONTENT").toString();
											u=new InitUser().getUser(r3);
								     
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                         <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" id=\"");
      out.print(i-4444 );
      out.write("\">\r\n");
      out.write("                                            \r\n");
      out.write("                                            <tr onmouseover=\"have2(");
      out.print((i+2)*10+j );
      out.write(")\" onmouseout=\"have22(");
      out.print((i+2)*10+j );
      out.write(")\">\r\n");
      out.write("                                             <td width=\"16%\" rowspan=\"2\" align=\"center\"><img src=\"");
      out.print(u.getUpicname() );
      out.write("\" width=\"60\" height=\"60\" /></td>\r\n");
      out.write("                                             <td width=\"63%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t      <span class=\"STYLE1\">");
      out.print(r33 );
      out.write("</span>&nbsp;<span class=\"STYLE16\"> ");
      out.print(r4 );
      out.write("\t</span>&nbsp;&nbsp;&nbsp;&nbsp;\t\t\t\t\t\t\t\t\t\t     </td>\r\n");
      out.write("\t\t\t\t\t\t\t                  \r\n");
      out.write("                                           </tr>\r\n");
      out.write("                                           <tr>\r\n");
      out.write("                                              <td> <span class=\"STYLE17\">");
      out.print(r5 );
      out.write("</span></td>\r\n");
      out.write("                                           </tr>\r\n");
      out.write("                                           <tr>\r\n");
      out.write("                                             <td>&nbsp;</td>\r\n");
      out.write("                                             <td colspan=\"2\">\r\n");
      out.write("                                             \r\n");
      out.write("                                           &nbsp;\r\n");
      out.write("                                                \r\n");
      out.write("                                            </td>\r\n");
      out.write("                                           </tr>\r\n");
      out.write("                                           <tr>\r\n");
      out.write("                                             <td colspan=\"2\"><hr width=\"73%\" align=\"center\" size=\"1\"/></td>\r\n");
      out.write("                                           </tr>\r\n");
      out.write("                                         </table>\r\n");
      out.write("                                       <!--hufu--> ");
 }
      out.write("                                    </td>\r\n");
      out.write("                                   </tr>\r\n");
      out.write("                                   <form action=\"SerHandleSay\" method=\"post\">\r\n");
      out.write("                                   <tr>\r\n");
      out.write("                                     <td>\r\n");
      out.write("                                         <textarea name=\"hfarea\" id=\"");
      out.print(i );
      out.write("\" class=\"area\" cols=\"50\" rows=\"1\" style=\"height:20px\" onfocus=\"change3(");
      out.print(i );
      out.write(',');
      out.print(i-100 );
      out.write(")\"></textarea>                                     </td>\r\n");
      out.write("                                   </tr>\r\n");
      out.write("                                   <tr>\r\n");
      out.write("                                     <td><div id=\"");
      out.print(i-100 );
      out.write("\" style=\"display:none\">\r\n");
      out.write("                                       <input type=\"hidden\" name=\"sayid\" value=\"");
      out.print(sayid );
      out.write("\"/>\r\n");
      out.write("                                       <input type=\"hidden\" name=\"tag\" value=\"radd1\"/>\r\n");
      out.write("                                       <input  type=\"submit\" class=\"hf1\" value=\"\"/>\r\n");
      out.write("                                     <a href=\"javascript:void(0)\" class=\"STYLE2\" onclick=\"change4(");
      out.print(i );
      out.write(',');
      out.print(i-100 );
      out.write(")\">取消</a></div></td>\r\n");
      out.write("                                   </tr>\r\n");
      out.write("                                   </form>\r\n");
      out.write("\t\t\t\t\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t     <td >&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t   </tr>\r\n");
      out.write("                                 </table>\r\n");
      out.write("\t\t\t\t\t\t\t\t \r\n");
      out.write("                             <!--正文--></td>\r\n");
      out.write("                           </tr>\r\n");
      out.write("                         </table>\r\n");
      out.write("                       <!--33333333333-->  \r\n");
      out.write("                       ");
} 
      out.write("  \r\n");
      out.write("    <!-- 1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111 -->\r\n");
      out.write("  </li></ul>\r\n");
      out.write(" </div>\r\n");
      out.write("   <div align=\"center\"><font color=\"blue\" face=\"幼圆\" size=\"-1\"><a href=\"SerAddLetter?tag=page\">点击获取更多</a></font></div>\r\n");
      out.write("   <br/>\r\n");
      out.write("</div></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\t</td>\r\n");
      out.write("    <td width=\"20%\" valign=\"top\" height=auto bgcolor=\"#FFFFFF\"><table frame=lhs style=\"border-left-style:double\"  bordercolor=\"blue\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td>&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td bgcolor=\"#CCFFFF\" ><table width=\"150\" height=\"auto\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td><div align=\"center\" class=\"STYLE1\">时间</div></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td><div align=\"center\" class=\"STYLE3\">");
      out.print(new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()).substring(0,10));
      out.write("</div></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td>");

                 if(request.getSession().getAttribute("userid")==request.getSession().getAttribute("conid")){
      out.write("\r\n");
      out.write("        <table width=\"100%\" height=\"auto\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("            <br/>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td><div align=\"center\" class=\"STYLE1\">推荐好友</div></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td align=\"center\" valign=\"top\">\r\n");
      out.write("              <!--yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy-->\r\n");
      out.write("              \r\n");
      out.write("                \t \r\n");
      out.write("              \r\n");
      out.write("\t\t\t\t                <div class=\"rollBox\">\r\n");
      out.write("\t\t\t\t     <div class=\"LeftBotton\" onmousedown=\"ISL_GoUp()\" onmouseup=\"ISL_StopUp()\" onmouseout=\"ISL_StopUp()\"></div>\r\n");
      out.write("\t\t\t\t     <div class=\"Cont\" id=\"ISL_Cont\">\r\n");
      out.write("\t\t\t\t      <div class=\"ScrCont\">\r\n");
      out.write("\t\t\t\t       <div id=\"List1\">\r\n");
      out.write("\t\t\t\t      \r\n");
      out.write("\t\t\t\t        <!-- 图片列表 begin -->\r\n");
      out.write("\t\t\t\t        ");

						List<Map<String, Object>> listt=u.getIntroFri();
						for(int i=0;i<listt.size();i++){
							Map<String, Object> map=listt.get(i);
							String pic=map.get("UPICNAME").toString();
							String name=map.get("USERNAME").toString();
							String user=map.get("USERID").toString();
				        
      out.write("\r\n");
      out.write("\t\t\t\t         <div class=\"pic\">\r\n");
      out.write("\t\t\t\t\t\t <img src=\"");
      out.print(pic );
      out.write("\" width=\"70\" height=\"55\"/>\r\n");
      out.write("\t\t\t\t          <p><a href=\"SerMakeFriends?fri2=");
      out.print(user);
      out.write("&tag=add\"><font size=\"-1\">");
      out.print(name );
      out.write("</font></a></p>\r\n");
      out.write("\t\t\t\t         </div>  \r\n");
      out.write("\t\t\t\t         ");
} 
      out.write("        \r\n");
      out.write("\t\t\t\t        <!-- 图片列表 end -->\r\n");
      out.write("\t\t\t\t        \r\n");
      out.write("\t\t\t\t       </div>\r\n");
      out.write("\t\t\t\t       <div id=\"List2\"></div>\r\n");
      out.write("\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t     </div>\r\n");
      out.write("\t\t\t\t     <div class=\"RightBotton\" onmousedown=\"ISL_GoDown()\" onmouseup=\"ISL_StopDown()\" onmouseout=\"ISL_StopDown()\"></div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write(".rollBox{width:150px;overflow:hidden;padding:12px 0 5px 6px;}\r\n");
      out.write(".rollBox .LeftBotton{height:52px;width:19px;background:url(pictures/scroll.jpg) no-repeat 11px 0;overflow:hidden;float:left;display:inline;margin:25px 0 0 0;cursor:pointer;}\r\n");
      out.write(".rollBox .RightBotton{height:52px;width:20px;background:url(pictures/scroll.jpg) no-repeat -8px 0;overflow:hidden;float:left;display:inline;margin:25px 0 0 0;cursor:pointer;}\r\n");
      out.write(".rollBox .Cont{width:110px;overflow:hidden;float:left;}\r\n");
      out.write(".rollBox .ScrCont{width:1000px;}\r\n");
      out.write(".rollBox .Cont .pic{width:110px;float:left;text-align:center;}\r\n");
      out.write(".rollBox .Cont .pic img{padding:4px;background:#fff;border:1px solid #ccc;display:block;margin:0 auto;}\r\n");
      out.write(".rollBox .Cont .pic p{line-height:26px;color:#505050;}\r\n");
      out.write(".rollBox .Cont a:link,.rollBox .Cont a:visited{color:#626466;text-decoration:none;}\r\n");
      out.write(".rollBox .Cont a:hover{color:#f00;text-decoration:underline;}\r\n");
      out.write(".rollBox #List1,.rollBox #List2{float:left;}\r\n");
      out.write("-->\r\n");
      out.write("</style>\t\t\t\t   \r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("<!--//--><![CDATA[//><!--\r\n");
      out.write("//图片滚动列表 mengjia 070816\r\n");
      out.write("\r\n");
      out.write("var Speed = 3; //速度(毫秒)\r\n");
      out.write("var Space = 6; //每次移动(px)\r\n");
      out.write("var PageWidth = 110; //翻页宽度\r\n");
      out.write("var fill = 0; //整体移位\r\n");
      out.write("var MoveLock = false;\r\n");
      out.write("var MoveTimeObj;\r\n");
      out.write("var Comp = 0;\r\n");
      out.write("var AutoPlayObj = null;\r\n");
      out.write("GetObj(\"List2\").innerHTML = GetObj(\"List1\").innerHTML;\r\n");
      out.write("GetObj('ISL_Cont').scrollLeft = fill;\r\n");
      out.write("GetObj(\"ISL_Cont\").onmouseover = function(){clearInterval(AutoPlayObj);}\r\n");
      out.write("GetObj(\"ISL_Cont\").onmouseout = function(){AutoPlay();}\r\n");
      out.write("AutoPlay();\r\n");
      out.write("function GetObj(objName){if(document.getElementById){return eval('document.getElementById(\"'+objName+'\")')}else{return eval('document.all.'+objName)}}\r\n");
      out.write("function AutoPlay(){ //自动滚动\r\n");
      out.write(" clearInterval(AutoPlayObj);\r\n");
      out.write(" AutoPlayObj = setInterval('ISL_GoDown();ISL_StopDown();',1000); //间隔时间\r\n");
      out.write("}\r\n");
      out.write("function ISL_GoUp(){ //上翻开始\r\n");
      out.write(" if(MoveLock) return;\r\n");
      out.write(" clearInterval(AutoPlayObj);\r\n");
      out.write(" MoveLock = true;\r\n");
      out.write(" MoveTimeObj = setInterval('ISL_ScrUp();',Speed);\r\n");
      out.write("}\r\n");
      out.write("function ISL_StopUp(){ //上翻停止\r\n");
      out.write(" clearInterval(MoveTimeObj);\r\n");
      out.write(" if(GetObj('ISL_Cont').scrollLeft % PageWidth - fill != 0){\r\n");
      out.write("  Comp = fill - (GetObj('ISL_Cont').scrollLeft % PageWidth);\r\n");
      out.write("  CompScr();\r\n");
      out.write(" }else{\r\n");
      out.write("  MoveLock = false;\r\n");
      out.write(" }\r\n");
      out.write(" AutoPlay();\r\n");
      out.write("}\r\n");
      out.write("function ISL_ScrUp(){ //上翻动作\r\n");
      out.write(" if(GetObj('ISL_Cont').scrollLeft <= 0){GetObj('ISL_Cont').scrollLeft = GetObj('ISL_Cont').scrollLeft + GetObj('List1').offsetWidth}\r\n");
      out.write(" GetObj('ISL_Cont').scrollLeft -= Space ;\r\n");
      out.write("}\r\n");
      out.write("function ISL_GoDown(){ //下翻\r\n");
      out.write(" clearInterval(MoveTimeObj);\r\n");
      out.write(" if(MoveLock) return;\r\n");
      out.write(" clearInterval(AutoPlayObj);\r\n");
      out.write(" MoveLock = true;\r\n");
      out.write(" ISL_ScrDown();\r\n");
      out.write(" MoveTimeObj = setInterval('ISL_ScrDown()',Speed);\r\n");
      out.write("}\r\n");
      out.write("function ISL_StopDown(){ //下翻停止\r\n");
      out.write(" clearInterval(MoveTimeObj);\r\n");
      out.write(" if(GetObj('ISL_Cont').scrollLeft % PageWidth - fill != 0 ){\r\n");
      out.write("  Comp = PageWidth - GetObj('ISL_Cont').scrollLeft % PageWidth + fill;\r\n");
      out.write("  CompScr();\r\n");
      out.write(" }else{\r\n");
      out.write("  MoveLock = false;\r\n");
      out.write(" }\r\n");
      out.write(" AutoPlay();\r\n");
      out.write("}\r\n");
      out.write("function ISL_ScrDown(){ //下翻动作\r\n");
      out.write(" if(GetObj('ISL_Cont').scrollLeft >= GetObj('List1').scrollWidth){GetObj('ISL_Cont').scrollLeft = GetObj('ISL_Cont').scrollLeft - GetObj('List1').scrollWidth;}\r\n");
      out.write(" GetObj('ISL_Cont').scrollLeft += Space ;\r\n");
      out.write("}\r\n");
      out.write("function CompScr(){\r\n");
      out.write(" var num;\r\n");
      out.write(" if(Comp == 0){MoveLock = false;return;}\r\n");
      out.write(" if(Comp < 0){ //上翻\r\n");
      out.write("  if(Comp < -Space){\r\n");
      out.write("   Comp += Space;\r\n");
      out.write("   num = Space;\r\n");
      out.write("  }else{\r\n");
      out.write("   num = -Comp;\r\n");
      out.write("   Comp = 0;\r\n");
      out.write("  }\r\n");
      out.write("  GetObj('ISL_Cont').scrollLeft -= num;\r\n");
      out.write("  setTimeout('CompScr()',Speed);\r\n");
      out.write(" }else{ //下翻\r\n");
      out.write("  if(Comp > Space){\r\n");
      out.write("   Comp -= Space;\r\n");
      out.write("   num = Space;\r\n");
      out.write("  }else{\r\n");
      out.write("   num = Comp;\r\n");
      out.write("   Comp = 0;\r\n");
      out.write("  }\r\n");
      out.write("  GetObj('ISL_Cont').scrollLeft += num;\r\n");
      out.write("  setTimeout('CompScr()',Speed);\r\n");
      out.write(" }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("              <!--yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy-->\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      \r\n");
      out.write("      <!-- 444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444 -->\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td><table width=\"100%\" height=\"auto\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("           \r\n");
      out.write("            <tr>\r\n");
      out.write("              <td><div align=\"center\" class=\"STYLE1\"><a href=\"javascript:void(0)\" ondblclick=\"showfr()\" onclick=\"disshowfr()\">我的好友</a></div><br/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td align=\"center\" valign=\"top\" id=\"fr\" style=\"display:none\"><!--yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy-->\r\n");
      out.write("\t\t\t\t      \r\n");
      out.write("\t\t\t\t        <!-- 图片列表 begin -->\r\n");
      out.write("\t\t\t\t        ");

				         int listfrii=0;
				         List<Map<String, Object>> listfri=u.getFri(userid);
				         if(listfri!=null){
				        	 listfrii=listfri.size();
				         }
				         for(int i=0;i<listfrii;i++){
				        	 Map<String, Object> mapfri=listfri.get(i);
				        	 String uid=mapfri.get("USERID").toString();
				        	 UserBean u4=new InitUser().getUser(uid);
				         
      out.write("\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t <img src=\"");
      out.print(u4.getUpicname() );
      out.write("\" width=\"70\" height=\"55\"/>\r\n");
      out.write("\t\t\t\t          <p><a href=\"SerMakeFriends?fri2=");
      out.print(uid );
      out.write("&tag=changeqz\" target=\"_top\"><font size=\"-1\">");
      out.print(u4.getUsername() );
      out.write("</font></a></p>\r\n");
      out.write("\t\t\t\t      \r\n");
      out.write("\t\t\t\t         ");
} 
      out.write("        \r\n");
      out.write("\t\t\t\t        <!-- 图片列表 end -->\r\n");
      out.write("\t\t\t\t        \r\n");
      out.write("\t\t\t\t       ");
  }
      out.write("  \r\n");
      out.write("\r\n");
      out.write("              <!--yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy-->\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("</table>\r\n");
      out.write("<h5 align=\"center\"><font color=\"#C0C0C0\">Copyright&copy;2012-2015 四海兴唐单智版权所有  吉 ICP备11011334号-1 </font></h5>\r\n");
      out.write("<h5 align=\"center\"><font color=\"#C0C0C0\">联系我：421170702@qq.com|18744033060</font></h5>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
